export const FETCH_EXAM_DATA = "FETCH_EXAM_DATA";
export const DECREMENT_INDEX = "DECREMENT_INDEX";
export const INCREMENT_INDEX = "INCREMENT_INDEX";
export const FETCH_STUDENT_DETAILS = "FETCH_STUDENT_DETAILS";
export const FETCH_STUDENTS_LIST = "FETCH_STUDENTS_LIST";
export const FETCH_TEACHER_EXAMS = "FETCH_TEACHER_EXAMS";
